services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - ./.env
    networks:
      - resound_network
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - postgres_data:/postgres_data
  nuxt:
    build: ./app
    restart: always
    user: "node"
    depends_on:
      - postgres
    ports:
      - "${NUXT_PORT:-3000}:80"
    env_file:
      - ./.env
    networks:
      - resound_network
    volumes:
      - ${LIBRARY_PATH}:/library

volumes:
  postgres_data:

networks:
  resound_network: