version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: resound
    ports:
      - "44005:5432"
    volumes:
      - ./schema_pg.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: