services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    expose:
      - ${POSTGRES_PORT:-5432}
    env_file:
      - ./.env
    networks:
      - resound_network
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./.postgres_data:/var/lib/postgresql/data
  nuxt:
    build: 
      context: .
      args:
        UID: "${UID}"
        GID: "${GID}"
      dockerfile: docker/Dockerfile.prod
    restart: always
    user: "node"
    depends_on:
      - postgres
    ports:
      - "${NUXT_PORT:-3000}:80"
    env_file:
      - ./.env
    networks:
      - resound_network
    volumes:
      - ${LIBRARY_PATH}:/library
      - ./.data:/app/.data

networks:
  resound_network: