# Stage 1: Build
FROM node:22 AS build
WORKDIR /build

RUN corepack enable

COPY package.json package-lock.json* ./
RUN npm install
COPY . ./

# Stage 2: Run
FROM node:22
WORKDIR /app

COPY --from=build /build/.output/ /build

#RUN chown -R node:node /app
#USER "node"

ARG ENVIRONMENT=dev
ENV ENVIRONMENT=${ENVIRONMENT}
ENV PORT=80
ENV HOST=0.0.0.0

EXPOSE 80


CMD ["npm", "run", "dev", "--", "--port", "80"]

# DEBUG 
#CMD ["tail", "-f", "/dev/null"]