name: Tests Main

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: "Installing dependencies"
        run: npm install
      - name: "Running ESLINT"
        run: npm run lint
      - name: "Running tests"
        run: npm test
